//
//  CMDefault.h
//  YHT
//
//  Created by 付晨鸣 on 15/2/11.
//  Copyright (c) 2015年 puyun. All rights reserved.
//

#ifndef YHT_CMDefault_h
#define YHT_CMDefault_h

//#define APP_ID @"1003588511"


#define DEFAULT_NO_WEB @"NO_WEB"
#define DEFAULT_STR_LAST_UPDATE @"Last Updated"
#define DEFAULT_STR_RELEASE_TO_REFRESH @"Release to refresh..."
#define DEFAULT_STR_PULL_DOWN_TO_REFRESH @"Pull down to refresh..."
#define DEFAULT_STR_LOADING @"Loading..."
#define DEFAULT_STR_RELEASE_TO_LOAD_MORE @"Release to load more..."
#define DEFAULT_STR_PULL_UP_TO_LOAD_MORE @"Pull up to load more..."
#define DEFAULT_STR_LOADING_MORE @"Loading more..."

#define DEFAULT_NO_LOGIN  @"您还未登录!"

// 图片公共部分
#define DEFAULT_COMMEOT_IMAGEPATH @"COMMONIMAGEPATH"
// 发布帖子Id
#define DEFAULT_PUBLISH_NOTEID @"PUBLISHNOTEID"

// 通知
#define DEFAULT_ADDTAGS_NOTIFICATION @"ADDTAGSNOTIFICATION"
#define DEFAULT_ADD_TAGS  @"ADDTAGS"

#define DEFAULT_NOTEDESC_NOTIFICATION @"NOTEDESCNOTIFICATION"
#define DEFAULT_ADDNOTEDESC_TAGS  @"ADDNOTEDESC"

#define DEFAULT_NOTEIMAGE_NOTIFICATION @"NOTEIMAGE"
#define DEFAULT_NOTEIMAGENAME  @"NOTEIMAGE"
#define DEFAULT_NOTEIMAGEMARK @"NOTEMARK"
#define DEFAULT_NOTEIMAGEATTRIBUTES    @"NOTEIMAGEATTRIBUTES"
#define DEFAULT_NOTEIMAGETYPE  @"NOTEIMAGETYPE"
#define DEFAULT_NOTEIMAGETYPEADD @"ADD"
#define DEFAULT_NOTEIMAGETYPEEDIT @"EDIT"

#define DEFAULT_NOTEIMAGETAG   @"NOTEIMAGETAG"
#define DEFAULT_NOTEPLACE_NOTIFICATION @"NOTEPLACENOTIFICATION"
#define DEFAULT_NOTEPLACEID @"NOTEPLACEID"
#define DEFAULT_NOTEPLACENAME @"NOTEPLACENAME"
#define DEFAULT_NOTEPLACTYPE @"NOTEPLACETYPE"



//LA 增加
//订单列表监听
#define NOTIFICATION_DINGDAN_RELOAD @"NOTIFICATION_DINGDAN_RELOAD"



#endif
